UPDATE customer
SET c_mktsegment = CASE c_mktsegment
    WHEN 'AUTOMOBILE' THEN 'BUILDING'
    WHEN 'BUILDING' THEN 'FURNITURE'
    WHEN 'FURNITURE' THEN 'HOUSEHOLD'
    WHEN 'HOUSEHOLD' THEN 'MACHINERY'
    WHEN 'MACHINERY' THEN 'AUTOMOBILE'
END
WHERE c_custkey = FLOOR(RANDOM() * 3000000);

